Server:
  proxyFe:
    path: https://jiladahe1997-1256609098.cos.ap-chengdu.myqcloud.com
    port: 443
    prefix: /everything-house-fe

Client:
  webpack:
    publicPath: //jiladahe1997-1256609098.cos.ap-chengdu.myqcloud.com/everything-house-fe
    