name: publishNodeServer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
    - name: install webpack
      run: npm install webpack webpack-cli
    - name: package server
      run: |
        npm install cross-env
        cross-env NODE_ENV=prod webpack --config ./server/webpack.config.js
        apt-get install zip
        zip -r index.zip ./serverDist/
    - name: publish
      run: node ./publishNodeServer.js
    
